### ISSUE TITLE
Unexpected error while configuring: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by ryan-schroeder** [auth0/ad-ldap-connector#102]
Installing on linux; we've gotten a series of different errors while trying different things.  Initially, we were seeing "unable to get local issuer certificate" TLSSocket error.  Trying on a different host, we started to see a different error;
Unexpected error while configuring connection: {Error: self signed certificate in certificate chain
  at Error (native)
  at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
  at emitNone (events.js:86:13)
  at TLSSocket.emit (events.js:185:7)
  at TLSSocket._finishInit (_tls_wrap.js:610:8)
  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
[ < time > ] self signed certificate in certificate chain

Even though we've removed all certificates from the search path.  Leaving all the existinrg certificates in the searched paths causes the same error.

Any ideas would be amazing, thanks!

**Comment by chrisbroome** [comment]
You can run with `NODE_TLS_REJECT_UNAUTHORIZED=0` if you just want to ignore those errors

**Comment by philomory** [comment]
@ryan-schroeder Did you ever solve this?
