### ISSUE TITLE
Error binding to LDAP dn:  code: 80

### ISSUE THREAD

**Issue by leonasta** [auth0/ad-ldap-connector#125]
Hi,
when I start the server I get the error below..I double checked all the parameters on my config.json and I am sure that this ldap server works well.

Can someone help me?

Thanks

```
[2018-07-17 13:20:03] Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
[2018-07-17 13:20:03] Connection to ldap was closed.
[2018-07-17 13:20:03] Error binding to LDAP dn:
 code: 80
 message: 2__ldap://ldaps.sys.net:636 closed
[2018-07-17 13:20:03] Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
[2018-07-17 13:20:03] Connection to ldap was closed.
[2018-07-17 13:20:03] Error binding to LDAP dn:
 code: 80
 message: 3__ldap://ldaps.my_ldaps.net:636 closed
[2018-07-17 13:20:03] jsonwebtoken: expiresInMinutes and expiresInSeconds is deprecated. (C:\ad-ldap-connector\ws_validator.js:300:19)
Use "expiresIn" expressed in seconds.
[2018-07-17 13:20:03] auth0: Agent accepted.
```

**Comment by jholladay10** [comment]
Based on this code (from ldap.js), I'd say that your LDAP_BIND_USER in config.json is empty and you have not enabled anonymous LDAP searches.

  if (!nconf.get('ANONYMOUS_SEARCH_ENABLED')) {
    var LDAP_BIND_CREDENTIALS = nconf.get('LDAP_BIND_PASSWORD') || crypto.decrypt(nconf.get('LDAP_BIND_CREDENTIALS'));
    connection.bind(nconf.get("LDAP_BIND_USER"), LDAP_BIND_CREDENTIALS, function(err) {
      if(err){
        console.error("Error binding to LDAP", 'dn: ' + err.dn + '\n code: ' + err.code + '\n message: ' + err.message);
        return exit(1);
      }
