### ISSUE TITLE
Does not compile on RHEL 7

### ISSUE THREAD

**Issue by debdattam-hexaware** [auth0/ad-ldap-connector#154]
As instructed on https://auth0.com/docs/connector/install-other-platforms?a=b5IudSlQCpmDujZh2Xe1XYSGpn0IfxlQ&ticket=Jx6q34JE we are following till step npm install.

Getting following error.

5918 warn optional SKIPPING OPTIONAL DEPENDENCY: win-ca-ffi@github:jfromaniello/win-ca#support-other-stores (node_modules/win-ca-ffi):
5919 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for win-ca-ffi@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
5920 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    win32
5920 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
5920 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
5920 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

Detailed error file attached.

**Comment by debdattam-hexaware** [comment]
[2019-03-05T07_20_06_145Z-debug.log](https://github.com/auth0/ad-ldap-connector/files/2929768/2019-03-05T07_20_06_145Z-debug.log)

**Comment by goodspeed666** [comment]
I use CentOS 7, and got the problems, too.
When I change the leveldown & levelup version to 2.x, it can be compiled finally.
But I setup config.js and ran `node server.js` again, it will shown below.

```
[root@ldap auth0-adldap]# node server.js
[2019-03-13 01:21:38] Reading CA certificates from OPENSSLDIR
[2019-03-13 01:21:38] Reading CA certificates from /etc/pki/tls/certs
[2019-03-13 01:21:38] Adding 3 certificates
[2019-03-13 01:21:38] Loading settings from ticket: https://xxx.auth0.com/p/ad/6sVmRu6I/info
[2019-03-13 01:21:40] Local settings updated.
[2019-03-13 01:21:40] Certificates already exist, skipping certificate generation.
[2019-03-13 01:21:40] Configuring connection LDAP.
[2019-03-13 01:21:40]  > Posting certificates and signInEndpoint: http://ldap.xxx.tw:4000/wsfed
[2019-03-13 01:21:40] Connection LDAP configured.
[2019-03-13 01:21:40] Connector setup complete.
[2019-03-13 01:21:40] InitializationError: First argument must be an abstract-leveldown compliant store
    at new LevelUP (/opt/auth0-adldap/node_modules/levelup/lib/levelup.js:49:13)
    at LevelUP (/opt/auth0-adldap/node_modules/levelup/lib/levelup.js:33:12)
    at Object.<anonymous> (/opt/auth0-adldap/lib/cache.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```
