### ISSUE TITLE
Undefined responses during testing settings

### ISSUE THREAD

**Issue by yaleman** [auth0/ad-ldap-connector#167]
### Description

Testing the authentication config from the admin interface and command line provides "undefined" errors when requesting data.

When doing a "search by username" in the admin search box it works OK

Search box output:
```
{
  "dn": "uid=yaleman,cn=users,cn=accounts,dc=housenet,dc=yaleman,dc=org",
  "controls": [],
  "displayName": "James Hodgkinson",
  "cn": "James Hodgkinson",
  "objectClass": [
    "top",
    "person",
    "organizationalperson",
    "inetorgperson",
    "inetuser",
    "posixaccount",
    "krbprincipalaux",
    "krbticketpolicyaux",
    "ipaobject",
    "ipasshuser",
    "ipauser",
    "ipaSshGroupOfPubKeys",
    "mepOriginEntry"
  ],
  "loginShell": "/bin/bash",
  "initials": "JH",
  "gidNumber": "636800000",
  "gecos": "James Hodgkinson",
  "sn": "Hodgkinson",
  "homeDirectory": "/home/yaleman",
  "uid": "yaleman",
  "givenName": "James",
  "uidNumber": "636800001"
}
```
### Reproduction

Web: open admin interface, click on troubleshooting, then run. Output:

```
Troubleshooting AD LDAP connector

Reading CA certificates from OPENSSLDIR
Reading CA certificates from /usr/lib/ssl/certs
Adding 135 certificates
22:37:29 - info: No proxy server configured.
22:37:29 - info: ✭ Testing connectivity to Auth0... 
22:37:29 - info:   > Test endpoint: https://terminaloutcomes.au.auth0.com/test
22:37:29 - info: ✔ Connection to test endpoint succeeded.
22:37:29 - info: ✭ Testing hub connectivity (WS). 
22:37:29 - info: ✔ Connection to hub succeeded.
22:37:29 - info: ✭ Testing clock skew... 
22:37:29 - info: ✔ Everything OK. No clock skew detected.
22:37:29 - info: ✭ Testing certificates... 
22:37:29 - info:   > Local thumbprint: e0663c8e32b21f4c3f8dd36e7be028b4abe2b9b4
22:37:30 - info:   > Server thumbprint: e0663c8e32b21f4c3f8dd36e7be028b4abe2b9b4
22:37:30 - info: ✔ Local and server certificates match. 
22:37:30 - info: ✭ Running NLTEST... 
22:37:30 - warn:   > NLTEST can only run on Windows.
22:37:30 - info: ✭ Testing LDAP connectivity. 
22:37:30 - info:   > LDAP BASE: cn=users,cn=accounts,dc=housenet,dc=yaleman,dc=org
22:37:30 - info:   > Found user: undefined
22:37:30 - info:   > Found user: undefined
22:37:30 - info:   > Found user: undefined
22:37:30 - info:   > Found user: undefined
22:37:30 - info:   > Found user: undefined
22:37:30 - info: ✔ Connection to LDAP succeeded.
22:37:30 - info: Done!
```

Command line: run suggested command from documentation.

```
/opt/auth0-adldap$ sudo node -e "require('./lib/initConf'); var Users = require('./lib/users'); var users = new Users(); users._queue.push(function(){users.getByUserName('yaleman', function (err, user) { console.log(err); } ); });"
[eval]:1
require('./lib/initConf'); var Users = require('./lib/users'); var users = new Users(); users._queue.push(function(){users.getByUserName('yaleman', function (err, user) { console.log(err); } ); });
                                                                                                     ^

TypeError: Cannot read property 'push' of undefined
    at [eval]:1:102
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)
    at startup (bootstrap_node.js:164:9)
    at bootstrap_node.js:609:3
```

### Environment

> Please provide the following:

- **Version of this library used:** `https://github.com/auth0/ad-ldap-connector/archive/v5.0.9.tar.gz`
- **Other relevant versions (language, server software, OS, browser):** Ubuntu 18.04.1 LTS, node 8.10.0, LDAP Server is FreeIPA

### config.json (xxx = removed data)
```
{
  "LDAP_SEARCH_ALL_QUERY": "(objectClass=person)",
  "LDAP_SEARCH_QUERY": "(&(objectClass=person)(uid={0}))",
  "LDAP_USER_BY_NAME": "(uid={0})",
  "LDAP_BASE": "cn=users,cn=accounts,dc=housenet,dc=yaleman,dc=org",
  "LDAP_URL": "ldap://xxx.housenet.yaleman.org",
  "ANONYMOUS_SEARCH_ENABLED": true,
  "AD_HUB": "https://terminaloutcomes.au.auth0.com/lo/hub",
  "PROVISIONING_TICKET": "xxx",
  "WSFED_ISSUER": "terminaloutcomes.com",
  "CONNECTION": "auth-public-housenet-yaleman-org",
  "CLIENT_CERT_AUTH": false,
  "KERBEROS_AUTH": false,
  "FIREWALL_RULE_CREATED": false,
  "REALM": "urn:auth0:terminaloutcomes",
  "SITE_NAME": "auth-public-housenet-yaleman-org",
  "urn:auth0:terminaloutcomes": "https://terminaloutcomes.au.auth0.com/login/callback",
  "LDAP_BIND_CREDENTIALS": "xxxxx",
  "SERVER_URL": "http://auth0.housenet.yaleman.org:4000",
  "LAST_SENT_THUMBPRINT": "xxxxx",
  "TENANT_SIGNING_KEY": "xxx",
  "LDAP_BIND_USER": "uid=xxx,cn=users,cn=accounts,dc=housenet,dc=yaleman,dc=org",
  "ENABLE_WRITE_BACK": false,
  "ENABLE_ACTIVE_DIRECTORY_UNICODE_PASSWORD": false,
  "PORT": 37749,
  "LDAP_BIND_PASSWORD": "xxx"
```

### profileMapper.json
```
module.exports = function (raw_data) {
  var profile = {
    id: raw_data.uid,
    displayName: raw_data.displayName,
    name: {
      familyName: raw_data.sn,
      givenName: raw_data.givenName
    },
    nickname: raw_data['uid'],
    groups: [raw_data['uid']],
    emails: raw_data.mail
  };
  
  profile['sAMAccountName'] = raw_data['uid'];
  
  profile['distinguishedName'] = raw_data['dn'];

  profile['dn'] = raw_data['dn'];
  profile['st'] = raw_data['st'];
  profile['description'] = raw_data['description'];
  profile['postalCode'] = raw_data['postalCode'];
  profile['telephoneNumber'] = raw_data['telephoneNumber'];
  profile['co'] = raw_data['co'];
  profile['department'] = raw_data['department'];
  profile['company'] = raw_data['company'];
  profile['mailNickname'] = raw_data['mailNickname'];
  profile['sAMAccountType'] = raw_data['sAMAccountType'];
  profile['userPrincipalName'] = raw_data['krbPrincipalName'];
  profile['manager'] = raw_data['manager'] ? raw_data['manager'] : undefined;
  profile['organizationUnits'] = raw_data['organizationUnits'];
  
  
  // if your LDAP service provides verified email addresses, uncomment this:
  // profile['email_verified'] = true;
  
  // This will make the profile huge:
  // if (raw_data['thumbnailPhoto']) {
  //   profile['picture'] = 'data:image/bmp;base64,' +
  //     raw_data['thumbnailPhoto'].toString('base64');
  // }

  return profile;
};
````

**Comment by yaleman** [comment]
Turns out the undefined is from [this line](https://github.com/auth0/ad-ldap-connector/blob/master/troubleshoot.js#L304) which is only showing `entry.object.sAMAccountName || entry.object.mail || entry.object.name` from the LDAP query, which hasn't used the profile mapping yet.

Changed the line to:

`logger.info('  > Found user: %s', entry.object.sAMAccountName || entry.object.uid || entry.object.mail || entry.object.name);` and I got valid data from my IPA server.
